eureka:
  client:
    register-with-eureka: true #从Eureka Server服务的列表只读备份，然后缓存在本地
    registry-fetch-interval-seconds: 5 #`每隔30秒`会重新获取并更新数据
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    lease-expiration-duration-in-seconds: 10 # 10秒即过期
    lease-renewal-interval-in-seconds: 5 # 5秒一次心跳

feign:
  hystrix:
    enabled: true #开启熔断

# 线程隔离
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 #熔断超时时间
          strategy: SEMAPHORE

ribbon:
  ReadTimeout: 60000 #通信超时时间
  ConnectTimeout: 60000 #连接超时时间

spring:
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true # 即在获取不到远程配置时，立即失败，但是用下边的配置进行重试
      retry:
        initial-interval: 2000 #最初重试间隔为 1000 毫秒
        max-interval: 10000 #最长重试间隔为 2000 毫秒
        multiplier: 2 #每次重试失败后，重试间隔所增加的倍数
        max-attempts: 10 #最多重试 6 次
  datasource:
    url: jdbc:mysql://212.129.249.243:3306/mall?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: xmf123456
    driver-class-name: com.mysql.jdbc.Driver
  hikari:
    idle-timeout: 60000
    maximum-pool-size: 30
    minimum-idle: 10
  jackson:
    default-property-inclusion: always
    date-format: yyyy-MM-dd
    time-zone: GMT+8